### ISSUE TITLE
Sort releases by date

### ISSUE THREAD

**Issue by oalders** [PerlToolsTeam/dashboard#76]
The default sort order for releases appears to be alphabetical. In my case this brings up an Acme module that I wrote a long time ago and don't really care about. What I do care about is my more recent uploads, so I'd like to see those first be default ideally. If not, I'd like to be able to have that column be sortable. I feel like it was before, but I can't sort by it on the currently deployed site.

**Comment by davorg** [comment]
I think you can do this already. Look at Gabor' s config file. authors/SZABGAB.json
